name: claim-verification
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - transformers
      - requests
      - beautifulsoup4
      - sentence-transformers
      - vaderSentiment
      - textblob
